[package]
name = "koa-interfaces"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file = "../../NOTICE.md"
publish = false

[lib]
name = "koa_interfaces"
path = "src/lib.rs"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

[lints]
workspace = true