"""Public Python bindings for kOA common interfaces."""

from .client import (
    SCHEMA_PATHS,
    DeliveryGuarantee,
    DuplicateOutcome,
    EventEnvelope,
    Idempotency,
    IdentityContext,
    IdentityType,
    JobRequest,
    JobState,
    JobStatus,
    Ordering,
    SchemaBinding,
    SchemaCatalog,
    UnixHttpClient,
    VersionNegotiation,
)
from .errors import (
    ErrorCategory,
    ErrorDisposition,
    ErrorEnvelope,
    InterfaceValidationError,
    ProtocolError,
    RemoteError,
    TransportError,
)
from .health import (
    AuthoritativeOutcome,
    AvailabilityState,
    CapabilityExecutionState,
    CapabilitySnapshot,
    CapabilityState,
    HealthState,
    HealthStatus,
    Readiness,
    ReadinessClass,
)
from .receipts import (
    Correlation,
    DisclosureClass,
    ReceiptClass,
    ReceiptCommitState,
    ReceiptDecision,
    ReceiptEnvelope,
    ReceiptExecutionState,
    ReceiptOutcome,
)

__version__ = "0.1.0"

__all__ = [
    "SCHEMA_PATHS",
    "AuthoritativeOutcome",
    "AvailabilityState",
    "CapabilityExecutionState",
    "CapabilitySnapshot",
    "CapabilityState",
    "Correlation",
    "DeliveryGuarantee",
    "DisclosureClass",
    "DuplicateOutcome",
    "ErrorCategory",
    "ErrorDisposition",
    "ErrorEnvelope",
    "EventEnvelope",
    "HealthState",
    "HealthStatus",
    "Idempotency",
    "IdentityContext",
    "IdentityType",
    "InterfaceValidationError",
    "JobRequest",
    "JobState",
    "JobStatus",
    "Ordering",
    "ProtocolError",
    "Readiness",
    "ReadinessClass",
    "ReceiptClass",
    "ReceiptCommitState",
    "ReceiptDecision",
    "ReceiptEnvelope",
    "ReceiptExecutionState",
    "ReceiptOutcome",
    "RemoteError",
    "SchemaBinding",
    "SchemaCatalog",
    "TransportError",
    "UnixHttpClient",
    "VersionNegotiation",
]
