"""Public kOA integration surface for SemantiK Architect."""

from .artifact_bridge import (
    ArtifactAdmissionDecision,
    ArtifactAdmissionPort,
    ArtifactBridge,
    ArtifactBridgeResult,
    ArtifactBridgeState,
    CompiledArtifactCandidate,
)
from .bootstrap import (
    ADAPTER_VERSION,
    INTEGRATION_ID,
    OFFICIAL_DOCUMENTATION_MOUNT,
    SUBSYSTEM_CONTRACT_VERSION,
    AdapterConfig,
    SemantikArchitectAdapter,
    create_adapter,
)
from .capabilities import (
    AlignmentState,
    CapabilityId,
    CapabilitySnapshot,
    CapabilityState,
    CapabilityStatus,
    CapabilityUnavailable,
    default_snapshot,
    snapshot_from_external,
)
from .client import (
    ExternalIndeterminate,
    ExternalProtocolError,
    ExternalRejected,
    ExternalResponse,
    ExternalUnavailable,
    SemantikArchitectClient,
    SemantikClientError,
    Transport,
)
from .compiler_jobs import (
    KNOWLEDGE_RELEASE_CHANNEL,
    CompilerJobCoordinator,
    CompilerJobRequest,
    CompilerJobResult,
    CompilerJobState,
)
from .health import ExternalState, HealthReport, HealthService, Liveness, Readiness
from .receipts import (
    CommitState,
    Decision,
    ExecutionState,
    IntegrationReceipt,
    ReceiptOutcome,
    make_receipt,
)
from .runtime_packs import (
    KNOWLEDGE_RELEASE_CHANNEL as LANGUAGE_PACK_RELEASE_CHANNEL,
    LANGUAGE_PACK_ARTIFACT_CLASS,
    LANGUAGE_PACK_SCHEMA,
    LanguagePackBridge,
    LanguagePackCandidate,
    LanguagePackPreparationResult,
    LanguagePackPreparationState,
    LanguagePackValidationDecision,
    LanguagePackValidationPort,
)

__all__ = [
    "ADAPTER_VERSION",
    "INTEGRATION_ID",
    "KNOWLEDGE_RELEASE_CHANNEL",
    "LANGUAGE_PACK_SCHEMA",
    "LANGUAGE_PACK_ARTIFACT_CLASS",
    "LANGUAGE_PACK_RELEASE_CHANNEL",
    "OFFICIAL_DOCUMENTATION_MOUNT",
    "SUBSYSTEM_CONTRACT_VERSION",
    "AdapterConfig",
    "AlignmentState",
    "ArtifactAdmissionDecision",
    "ArtifactAdmissionPort",
    "ArtifactBridge",
    "ArtifactBridgeResult",
    "ArtifactBridgeState",
    "CapabilityId",
    "CapabilitySnapshot",
    "CapabilityState",
    "CapabilityStatus",
    "CapabilityUnavailable",
    "CommitState",
    "CompiledArtifactCandidate",
    "CompilerJobCoordinator",
    "CompilerJobRequest",
    "CompilerJobResult",
    "CompilerJobState",
    "Decision",
    "ExecutionState",
    "ExternalIndeterminate",
    "ExternalProtocolError",
    "ExternalRejected",
    "ExternalResponse",
    "ExternalState",
    "ExternalUnavailable",
    "HealthReport",
    "HealthService",
    "IntegrationReceipt",
    "LanguagePackBridge",
    "LanguagePackCandidate",
    "LanguagePackPreparationResult",
    "LanguagePackPreparationState",
    "LanguagePackValidationDecision",
    "LanguagePackValidationPort",
    "Liveness",
    "Readiness",
    "ReceiptOutcome",
    "SemantikArchitectAdapter",
    "SemantikArchitectClient",
    "SemantikClientError",
    "Transport",
    "create_adapter",
    "default_snapshot",
    "make_receipt",
    "snapshot_from_external",
]
